ncgc:
  nureAddress: Nauky Ave. 14, Kharkiv
  cist:
    baseUrl: http://cist.nure.ua/ias/app/tt/
    apiKey: yourKey # Required if classes are loaded

  tasks:
    timeout: 00:08:00.000 # 8 minutes. Timeout for interruption, required for Google Cloud Function
    concurrency: 5 # Max number of requests to run simultaneously
    progress:
      backend: file
      backendConfigs:
        file:
          unix: /var/tmp/ncgc/interrupted-tasks.json
          win: %SystemRoot%\Temp\ncgc\interrupted-tasks.json
  caching:
    maxExpiration:
      hours: 5
      minutes: 30
    cist:
      priorities:
        auditories: [file, http]
        groups: [file, http]
        events: [file, http]
      configs:
        file:
          directory:
            unix: /var/tmp/ncgc/cache/cist
            win: %SystemRoot%\Temp\ncgc\cache\cist
  google:
    idPrefix: cist
    groupEmailPrefix: g
    calendar:
      timeZone: Europe/Kiev # timezone for event creation
      eventsTaskContextStorage:
        backend: file
        backendConfigs:
          file:
            unix: /var/tmp/ncgc/google/events-task-context.json
            win: %SystemRoot%\Temp\ncgc\google\events-task-context.json
    auth:
      adminDirectoryKey: ./keys/cist-calendar.json # either object for JSON key or (string) path to file
      calendarKey: ./keys/cist-calendar.json # either object for JSON key or (string) path to file
      adminSubjectEmail: yourEmail@nure.ua # Required for admin. email of user belonging to the domain of G Suite.
      calendarUserEmail: yourEmail@nure.ua # User, that will be organizer for all Google events.
    quotas:
      adminDirectoryApi:
        daily: 150000 # daily limit
        period: 100000 # ms
        queries: 4000 # per period.
        burst: false # true: try load all resources at once and then throttle when limit is exhausted; false: make requests with equal interval all the time. False is used because it works more reliable for now
      calendarApi:
        daily: 1000000 # daily limit
        period: 100000 # ms
        queries: 100000000 # per period
        burst: false # true: try load all resources at once and then throttle when limit is exhausted; false: make requests with equal interval all the time.
