cist:
  baseUrl: http://cist.nure.ua/ias/app/tt/
  apiKey: yourKey # Required if classes are loaded

google:
  idPrefix: cist
  auth:
    subjectEmail: yourEmail # Required for admin. email of user belonging to the domain of G Suite.
    calendarKeyFilepath: ./keys/cist-calendar.json
    adminKeyFilepath: ./keys/cist-calendar.json
  quotas:
    directoryApi:
      daily: 150_000 # daily limit
      period: 100_000 # ms
      queries: 1500 # per period
