cist:
  baseUrl: http://cist.nure.ua/ias/app/tt/
  apiKey: yourKey # Required if classes are loaded

google:
  idPrefix: cist
  auth:
    subjectEmail: yourEmail # Required for admin. email of user belonging to the domain of G Suite.
    calendarKeyFilepath: ./keys/cist-calendar.json
    directoryKeyFilepath: ./keys/cist-calendar.json
  quotas:
    directoryApi:
      daily: 150_000 # daily limit
      period: 100_000 # ms
      queries: 460 # per period. Fallback to 425 if problems. Actual is 1500, but decreased for reliability
      burst: false # true: try load all 1500 queries at once and throttle; false: make request with equal interval all the time. False is used because it works more reliable for now
